### ISSUE TITLE
模型下载过慢，已存在模型的情况下依然会下载模型

### ISSUE THREAD

**Issue by Dean-ZhenYao-Wang** [StartHua/Comfyui-Mine-PhotoMaker#2]
百兆光纤，你这个脚本下载速度却只有几百K，我下载其他模型都可快了，用IDM下载更快。哪怕是用IDM下载photomaker-v1.bin也能到好几M。
而且我如果单独下载这个模型后，放到model目录下，启动程序，依然会下载这个模型。

**Comment by klossm** [comment]
我不是光纤，下载速度也很快，和作者的脚本关系不大，你手动下的是photomaker-v1.bin命名的模型，直接丢进去当然不会识别啊，因为默认所有的模型是以缓存形式下载的，缓存形式下载的模型名称会变，模型会分为数个文件下载，比如RealVisXL_V3.0.safetensors这个模型，直接去下载模型然后丢ComfyUI\custom_nodes\Comfyui-Mine-PhotoMaker\modes 里当然不行，默认下载会有models--SG161222--RealVisXL_V3.0和models--TencentARC--PhotoMaker这2个文件夹位于ComfyUI\custom_nodes\Comfyui-Mine-PhotoMaker\modes目录下，里面都是多个以缓存命名形式的模型文件，必须是按缓存模型的形式它才能识别，所以最好不要自己手动下载，除非你很了解模型缓存的结构和命名形式，然后自己去抱脸去下载

**Comment by usaking12** [comment]
推荐下载半天，多次。手动下载2个模型不知道放在哪里，推荐手动下载。

**Comment by Dean-ZhenYao-Wang** [comment]
> 推荐下载半天，多次。手动下载2个模型不知道放在哪里，推荐手动下载。

已解决一个模型的手动下载问题。https://github.com/TencentARC/PhotoMaker/issues/31#issuecomment-1895554268
另外一个不知道如何解决，只能等慢慢下载了。
